export const FETCH_BOOKED_USERS = 'FETCH_BOOKED_USERS'
export const SET_USER = 'SET_USER'
export const SET_ERRORS = 'SET_ERRORS'
export const SET_DOCTOR_DETAILS = 'SET_DOCTOR_DETAILS'
export const SET_CURRENT_WORKING_PLACE = 'SET_CURRENT_WORKING_PLACE'
export const SET_LOADING = 'SET_LOADING'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const CURRENT_BOOKINGS_NOW = 'CURRENT_BOOKINGS_NOW'


